### ISSUE TITLE
[bug] UnicodeDecodeError during server startup

### ISSUE THREAD

**Issue by RedstoneAlmeida** [EndstoneMC/endstone#22]
**Describe the bug**
```
(venv) PS T:\Python Projects\ProjectTestEndstone> endstone
[2024-06-24 22:17:52.610 ERROR] [endstone._internal.bootstrap] 'utf-8' codec can't decode byte 0x88 in position 13: invalid start byte
Traceback (most recent call last):
  File "T:\Python Projects\ProjectTestEndstone\venv\Lib\site-packages\endstone\_internal\bootstrap\__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "T:\Python Projects\ProjectTestEndstone\venv\Lib\site-packages\endstone\_internal\bootstrap\__init__.py", line 74, in cli
    exit_code = bootstrap.run()
                ^^^^^^^^^^^^^^^
  File "T:\Python Projects\ProjectTestEndstone\venv\Lib\site-packages\endstone\_internal\bootstrap\base.py", line 196, in run
    self._create_process()
  File "T:\Python Projects\ProjectTestEndstone\venv\Lib\site-packages\endstone\_internal\bootstrap\windows.py", line 106, in _create_process
    self._add_loopback_exemption()
  File "T:\Python Projects\ProjectTestEndstone\venv\Lib\site-packages\endstone\_internal\bootstrap\windows.py", line 97, in _add_loopback_exemption
    if sid not in ret.stdout.decode():
                  ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 13: invalid start byte
```

**To Reproduce**
Execute command: pip install endstone
After: endstone

**Expected behavior**
Running code

**Screenshots**
![image](https://github.com/EndstoneMC/endstone/assets/15146680/b6e0255a-98d3-4ac8-98d6-cb29bca483fd)

**Details (please complete the following information):**
 - OS: Windows 10 Home
 - Endstone Version: IDK Sorry (i imagine if latest)

**Comment by wu-vincent** [comment]
Thanks for reporting this. I suspect this might be a bug on systems whose default encoding scheme isn't UTF-8.

Can you please execute the following Python commands and provide the output? Thanks.

```python
import sys
print(sys.stdout.encoding)
```

**Comment by wu-vincent** [comment]
This issue should be fixed by https://github.com/EndstoneMC/endstone/commit/f5202796895ce911faf4d27f1c82dc2da6857b47.
